using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Reflection;

namespace ConsoleApp1
{
    class ExampleCodeToCompile
    {
        static void main(string[] args)
        {
            //string path = "<Generated by CodeGen.cs>";
            //<Code Generated by CodeGen.cs>

            //AppDomain.CurrentDomain.Load(assemble(path).GetName());
        }
        static Assembly assemble(string path)
        {
            Assembly a = Assembly.LoadFrom(path);
            return a;
        }
    }
}
